site_name: 教程
docs_dir: "mkdocs"
repo_url: https://github.com/idcos/cloudiac-docs
repo_name: cloudiac-docs
edit_uri: edit/master/tutorials/mkdocs/
theme:
  language: zh
  name: material
  logo: assets/svg/icon.svg
  favicon: assets/svg/icon.svg
  palette:
    primary: deep purple
  icon:
    repo: fontawesome/brands/github
plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\-\.]+' # 分词分隔符
extra:
  version:
    provider: mike
    default: latest
extra_css:
  - "assets/css/custom.css"
  - "assets/css/simpleLightbox.min.css"
extra_javascript:
  - "assets/js/jquery.min.js"
  - "assets/js/simpleLightbox.min.js"
  - "assets/js/custom.js"
markdown_extensions:
  - markdown.extensions.attr_list
  - meta
  - toc:
      permalink: "#"
      baselevel: 1
      separator: "_"
  - footnotes
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:mermaid2.fence_mermaid"

nav:
  - "快速入门":
      - "创建组织和项目": quick-start/create-org-project.md
      - "创建云模板": quick-start/create-template.md
      - "部署环境": quick-start/deploy-env.md

  - "Registry":
    - "Provider 发布": "cases/provider-publish.md"
    - "Module 发布": "cases/module-publish.md"
    - "策略组发布": "cases/policy-group-publish.md"
    - "获取签名密钥": cases/create-gpg-key.md
    - "添加签名密钥": cases/add-gpg-key.md
    - "vcs集成": cases/create-vcs.md
    - "token获取": cases/token.md

  - "用户场景":
    - "创建 aliyun ecs": "cases/aliyun-ecs.md"
    - "本地资源创建": "cases/all-in-one-example.md"
    - "资源变更检测": "cases/drift_detection.md"
    - "添加SSH密钥": "cases/ssh_key.md"
    - "云模板terraform版本选择": "cases/cloud_template.md"
    - "通过 Git 仓库创建策略组": "cases/git-create-policy-group.md"
    - "检测资源合规": "cases/check-policy.md"
    - "环境创建成功后定时销毁": "cases/env-auto-destroy.md"
    - "添加部署失败通知": "cases/deploy-failed-notification.md"
    - "使用 Registry 的 Provider": "cases/use-provider.md"
    - "使用合规策略限制测试环境的机器规格": "cases/opa-instance-type.md"
    - "使用 Registry 中的策略组": "cases/registry-policygroup.md"
    - "通过 tfvars 文件预定义变量": "cases/tfvars.md"
