site_name: 教程
docs_dir: "mkdocs"
repo_url: https://github.com/idcos/cloudiac-docs
repo_name: cloudiac-docs
edit_uri: edit/master/tutorials/mkdocs/
theme:
  language: zh
  name: material
  logo: assets/svg/icon.svg
  favicon: assets/svg/icon.svg
  palette:
    primary: deep purple
  icon:
    repo: fontawesome/brands/github
plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\-\.]+' # 分词分隔符
extra:
  version:
    provider: mike
    default: latest
extra_css:
  - "assets/css/custom.css"
  - "assets/css/simpleLightbox.min.css"
extra_javascript:
  - "assets/js/jquery.min.js"
  - "assets/js/simpleLightbox.min.js"
  - "assets/js/custom.js"
markdown_extensions:
  - markdown.extensions.attr_list
  - meta
  - toc:
      permalink: "#"
      baselevel: 1
      separator: "_"
  - footnotes
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:mermaid2.fence_mermaid"

nav: {}
